# Generated by Django 4.2.5 on 2023-09-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bankbranch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankBranch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
