# Generated by Django 4.2.5 on 2023-09-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='distname',
            new_name='district',
        ),
    ]
